# Generated by Django 4.2.18 on 2025-02-02 17:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('file_id', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('duration', models.IntegerField()),
                ('file_name', models.CharField(max_length=256)),
                ('mime_type', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=256)),
                ('performer', models.CharField(max_length=256)),
                ('file_unique_id', models.CharField(max_length=256)),
                ('file_size', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=256)),
                ('parent_category_id', models.CharField(default=' ', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('tg_user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=254)),
                ('username', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AudioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugs.category')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ugs.audio')),
            ],
            options={
                'unique_together': {('category_id', 'file_id')},
            },
        ),
    ]
